language: python

python:
  - "2.7"
  - "3.6"
  - "pypy"

env:
  - CODECLIMATE_REPO_TOKEN=4967416d540739937e0eebfb13a3cf2f8dfbddd762f2b1ec800e83d18fb5efbb

install:
  - pip install -r requirements.txt
  - pip install "coverage>4.0,<4.4" # https://bitbucket.org/ned/coveragepy/issues/578/incomplete-file-path-in-xml-report
  - pip install codeclimate-test-reporter

script:
  - THIS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  - export PYTHONPATH=$THIS_DIR:$PYTHONPATH
  - python setup.py test
  - codeclimate-test-reporter

sudo: false
