name: Build and Test

on: [push, pull_request]

jobs:
  build:
    name: Test on Python ${{ matrix.python-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['2.7', '3.5', '3.6', '3.7', '3.8', 'pypy-2.7-v7.3.5', 'pypy-3.6.12-v7.3.3', 'pypy-3.7.10-v7.3.5']
        os: [ubuntu-latest]  #, windows-latest, macOS-latest]
      fail-fast: false
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Show system
      run: |
        python --version
        uname -a
        lsb_release -a
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_test.txt
    - name: Test with nose
      run: |
        coverage run -m nose tests/*
        coverage report
    - name: Code Climate Coverage Action
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: coverage xml
        debug: true